namespace FHIR_Concept_Map_Builder;

public static class HsLocCodes
{
    public static readonly Dictionary<string, string> Codes = new()
    {
        { "1026-4", "Burn Critical Care" },
        { "1042-1", "Pediatric Burn Critical Care" },
        { "1028-0", "Medical Cardiac Critical Care" },
        { "1032-2", "Surgical Cardiothoracic Critical Care" },
        { "1043-9", "Pediatric Surgical Cardiothoracic Critical Care" },
        { "1220-3", "Long Term Acute Care Intensive Care Unit" },
        { "1222-9", "Long Term Acute Care Pediatric Intensive Care Unit" },
        { "1027-2", "Medical Critical Care" },
        { "1044-7", "Pediatric Medical Critical Care" },
        { "1029-8", "Medical-Surgical Critical Care" },
        { "1045-4", "Pediatric Medical-Surgical Critical Care" },
        { "1035-5", "Neurologic Critical Care" },
        { "1031-4", "Neurosurgical Critical Care" },
        { "1046-2", "Pediatric Neurosurgical Critical Care" },
        { "1040-5", "Neonatal Critical Care (Level III)" },
        { "1269-0", "Neonatal Critical Care (Level IV)" },
        { "1272-4", "Onsite Overflow Critical Care" },
        { "1223-7", "Oncology Medical Critical Care" },
        { "1225-2", "Oncology Medical-Surgical Critical Care" },
        { "1233-6", "Oncology Pediatric Critical Care" },
        { "1224-5", "Oncology Surgical Critical Care" },
        { "1034-8", "Prenatal Critical Care" },
        { "1033-0", "Respiratory Critical Care" },
        { "1047-0", "Pediatric Respiratory Critical Care" },
        { "1030-6", "Surgical Critical Care" },
        { "1048-8", "Pediatric Surgical Critical Care" },
        { "1025-6", "Trauma Critical Care" },
        { "1049-6", "Pediatric Trauma Critical Care" },
        { "1039-7", "Neonatal Critical Care (Level II/III)" },
        { "1217-9", "Rehabilitation Ward (within freestanding Inpatient Rehabilitation Facility)" },
        { "1218-7", "Pediatric Rehabilitation Ward (within freestanding Inpatient Rehabilitation Facility)" },
        { "1212-0", "Mixed Age Mixed Acuity Unit" },
        { "1210-4", "Adult Mixed Acuity Unit" },
        { "1211-2", "Pediatric Mixed Acuity Unit" },
        { "1236-9", "Oncology Mixed Acuity Unit (all ages)" },
        { "1096-7", "Operating Room/Suite" },
        { "1005-8", "Cardiac Catheterization Room/Suite" },
        { "1095-9", "Cesarean Section Room/Suite" },
        { "1203-9", "Interventional Radiology" },
        { "1097-5", "Post-Anesthesia Care Unit/Recovery Room" },
        { "1198-1", "Dialysis Specialty Care Area" },
        { "1091-8", "Pediatric Dialysis Specialty Care Area" },
        { "1092-6", "Solid Organ Transplant Specialty Care Area" },
        { "1093-4", "Pediatric Solid Organ Transplant Specialty Care Area" },
        { "1099-1", "Adult Step Down Unit" },
        { "1041-3", "Special Care Nursery (Level II)" },
        { "1227-8", "Oncology Step Down Unit" },
        { "1100-7", "Pediatric Step Down Unit" },
        { "1205-4", "Antenatal Care Ward" },
        { "1052-0", "Burn Ward" },
        { "1078-5", "Pediatric Burn Ward" },
        { "1051-2", "Behavioral Health/Psych Ward" },
        { "1075-1", "Adolescent Behavioral Health Ward" },
        { "1077-7", "Pediatric Behavioral Health Ward" },
        { "1270-8", "Chemical Dependency Ward" },
        { "1053-8", "Ear, Nose, Throat Ward" },
        { "1079-3", "Pediatric Ear, Nose, Throat Ward" },
        { "1054-6", "Gastrointestinal Ward" },
        { "1056-1", "Gerontology Ward" },
        { "1055-3", "Genitourinary Ward" },
        { "1080-1", "Pediatric Genitourinary Ward" },
        { "1057-9", "Gynecology Ward" },
        { "1172-6", "School Infirmary" },
        { "1171-8", "Jail Unit" },
        { "1058-7", "Labor and Delivery Ward" },
        { "1059-5", "Labor, Delivery, Recovery, Postpartum Suite" },
        { "1221-1", "Long Term Acute Care Ward" },
        { "1214-6", "Long Term Acute Care Pediatric Ward" },
        { "1060-3", "Medical Ward" },
        { "1076-9", "Pediatric Medical Ward" },
        { "1061-1", "Medical-Surgical Ward" },
        { "1081-9", "Pediatric Medical-Surgical Ward" },
        { "1062-9", "Neurology Ward" },
        { "1082-7", "Pediatric Neurology Ward" },
        { "1063-7", "Neurosurgical Ward" },
        { "1083-5", "Pediatric Neurosurgical Ward" },
        { "1038-9", "Well Newborn Nursery (Level I)" },
        { "1271-6", "Onsite Overflow Ward" },
        { "1232-8", "Oncology General Hematology-Oncology Ward" },
        { "1235-1", "Oncology Pediatric General Hematology/Oncology Ward" },
        { "1231-0", "Oncology Hematopoietic Stem Cell Transplant Ward" },
        { "1234-4", "Oncology Pediatric Hematopoietic Stem Cell Transplant Ward" },
        { "1226-0", "Oncology Leukemia Ward" },
        { "1229-4", "Oncology Leukemia-Lymphoma Ward" },
        { "1228-6", "Oncology Lymphoma Ward" },
        { "1230-2", "Oncology Solid Tumor Ward" },
        { "1064-5", "Ophthalmology Ward" },
        { "1065-2", "Orthopedic Ward" },
        { "1084-3", "Pediatric Orthopedic Ward" },
        { "1067-8", "Plastic Surgery Ward" },
        { "1068-6", "Postpartum Ward" },
        { "1069-4", "Pulmonary Ward" },
        { "1070-2", "Rehabilitation Ward (within Hospital)" },
        { "1085-0", "Pediatric Rehabilitation Ward (within Hospital)" },
        { "1072-8", "Surgical Ward" },
        { "1086-8", "Pediatric Surgical Ward" },
        { "1071-0", "Stroke (Acute) Ward" },
        { "1066-0", "Orthopedic Trauma Ward" },
        { "1208-8", "Telemetry Ward" },
        { "1073-6", "Vascular Surgery Ward" },
        { "1102-3", "Chronic Care Unit" },
        { "1103-1", "Chronic Alzheimer's Unit" },
        { "1104-9", "Chronic Behavioral Health/Psych Unit" },
        { "1165-0", "Inpatient Hospice" },
        { "1164-3", "Ventilator Dependent Unit" },
        { "1105-6", "Chronic Rehabilitation Unit" },
        { "1260-9", "Long Term Care Facility Bariatric Unit" },
        { "1255-9", "Long Term Care Facility Dementia Unit" },
        { "1258-3", "Long Term Care Facility General Nursing Unit" },
        { "1254-2", "Long Term Care Facility Inpatient Hospice Unit" },
        { "1256-7", "Long Term Care Facility Psychiatric Unit" },
        { "1257-5", "Long Term Care Facility Skilled Nursing-Short Term Rehabilitation Unit" },
        { "1259-1", "Long Term Care Facility Ventilator Dependent Unit" },
        { "1262-1", "Home Hemodialysis" },
        { "1160-1", "Urgent Care Center" },
        { "1108-0", "Emergency Department" },
        { "1109-8", "Pediatric Emergency Department" },
        { "1174-2", "Mobile Emergency Services/EMS" },
        { "1242-7", "Outpatient Operating Room/Suite (Attached)" },
        { "1248-4", "Pediatric Outpatient Operating Room/Suite (Attached)" },
        { "1244-3", "Outpatient Operating Room/Suite (Detached)" },
        { "1249-2", "Pediatric Outpatient Operating Room/Suite (Detached)" },
        { "1169-2", "Post-Anesthesia Care Unit" },
        { "1162-7", "24-Hour Observation Area" },
        { "1243-5", "Ambulatory Surgery Center" },
        { "1246-8", "Outpatient Ambulatory Pediatric Surgery Center" },
        { "1247-6", "Outpatient Ambulatory Plastic Surgery Center" },
        { "1245-0", "Ambulatory Surgery Recovery Room" },
        { "1019-9", "Specimen Collection Area (Healthcare)" },
        { "1139-5", "Well Baby Clinic" },
        { "1141-1", "Physician's Office" },
        { "1110-6", "Allergy Clinic" },
        { "1145-2", "Behavioral Health Clinic" },
        { "1146-0", "Pediatric Behavioral Health Clinic" },
        { "1147-8", "Blood Collection Center" },
        { "1113-0", "Cardiology Clinic" },
        { "1112-2", "Cardiac Rehabilitation Center" },
        { "1148-6", "Continence Clinic" },
        { "1150-2", "Dental Clinic" },
        { "1130-4", "Pediatric Dental Clinic" },
        { "1115-5", "Dermatology Clinic" },
        { "1131-2", "Pediatric Dermatology Clinic" },
        { "1116-3", "Diabetes-Endocrinology Clinic" },
        { "1132-0", "Pediatric Diabetes-Endocrinology Clinic" },
        { "1153-6", "Outpatient Hemodialysis Clinic" },
        { "1268-2", "Outpatient Hemodialysis Clinic - Acute Kidney Injury" },
        { "1126-2", "Ear, Nose, Throat Clinic" },
        { "1117-1", "Family Medicine Clinic" },
        { "1018-1", "Infusion Center" },
        { "1122-1", "Genetics Clinic" },
        { "1118-9", "Gastrointestinal Clinic" },
        { "1119-7", "Pediatric Gastrointestinal Clinic" },
        { "1121-3", "Gynecology Clinic" },
        { "1017-3", "Hyperbaric Oxygen Center" },
        { "1219-5", "Outpatient Hemodialysis Clinic (in Inpatient Facility)" },
        { "1154-4", "HIV Clinic" },
        { "1161-9", "Holistic Medicine Center" },
        { "1200-5", "Hematology-Oncology Clinic" },
        { "1136-1", "Pediatric Hematology-Oncology Clinic" },
        { "1170-0", "School or Prison Infirmary" },
        { "1120-5", "Medical Clinic" },
        { "1123-9", "Neurology Clinic" },
        { "1151-0", "Occupational Health Clinic" },
        { "1124-7", "Ophthalmology Clinic" },
        { "1125-4", "Orthopedic Clinic" },
        { "1133-8", "Pediatric Orthopedic Clinic" },
        { "1149-4", "Ostomy Clinic" },
        { "1152-8", "Occupational Therapy Clinic" },
        { "1127-0", "Pain Clinic" },
        { "1128-8", "Pediatric Clinic" },
        { "1129-6", "Pediatric Cardiology Center" },
        { "1137-9", "Pediatric Nephrology Clinic" },
        { "1156-9", "Prenatal Clinic" },
        { "1140-3", "Podiatry Clinic" },
        { "1202-1", "Physical Therapy Clinic" },
        { "1157-7", "Pulmonary Clinic" },
        { "1155-1", "Rehabilitation Clinic" },
        { "1142-9", "Rheumatology Clinic" },
        { "1138-7", "Pediatric Rheumatology Clinic" },
        { "1143-7", "Surgical Services Clinic" },
        { "1134-6", "Pediatric Scoliosis Clinic" },
        { "1158-5", "Speech Therapy Clinic" },
        { "1207-0", "Therapeutic Apheresis Clinic" },
        { "1144-5", "Wound Center" },
        { "1159-3", "Wound Ostomy Continence Clinic" },
        { "1007-4", "Endoscopy Suite" },
        { "1009-0", "Pulmonary Function Testing" },
        { "1008-2", "Radiology" },
        { "1178-3", "Transport Service" },
        { "1176-7", "Mobile Blood Collection Center" },
        { "1175-9", "Mobile MRI/CT" },
        { "1250-0", "Facility-wide Inpatient (FacWIDEIn)" },
        { "1251-8", "Facility-wide Outpatient (FacWIDEOut)" },
        { "1206-2", "Float" },
        { "1209-6", "Treatment Room" },
        { "1020-7", "Sleep Study Unit" },
        { "1189-0", "Morgue/Autopsy Room" },
        { "1196-5", "Specimen Collection Area (Community)" },
        { "1195-7", "Blood Collection (Blood Drive Campaign)" },
        { "1192-4", "Home Care" },
        { "1194-0", "Home-based Hospice" },
        { "1204-7", "Location outside facility" },
        { "1106-4", "Assisted Living Area" },
        { "1010-8", "General Laboratory" },
        { "1185-8", "Blood Bank" },
        { "1011-6", "Clinical Chemistry Laboratory" },
        { "1261-7", "Centralized Transfusion Service" },
        { "1012-4", "Hematology Laboratory" },
        { "1013-2", "Histology-Surgical Pathology Laboratory" },
        { "1014-0", "Microbiology Laboratory" },
        { "1015-7", "Serology Laboratory" },
        { "1016-5", "Virology Laboratory" },
        { "1184-1", "Administrative Areas" },
        { "1186-6", "Central Sterile Supply" },
        { "1181-7", "Physical Plant Operations Center" },
        { "1188-2", "Facility Grounds" },
        { "1182-5", "Housekeeping/Environmental Services" },
        { "1183-3", "Laundry Room" },
        { "1179-1", "Pharmacy" },
        { "1180-9", "Public Area in Facility" },
        { "1190-8", "Soiled Utility Area" },
        { "1187-4", "Central Trash Area" },
        { "1265-8", "Inpatient Psychiatric Facility Unit(s)" },
        { "1264-1", "Inpatient Rehabilitation Facility Unit(s)" },
        { "1263-3", "Non-CMS Hospital Units" }
    };
}